server.port=8080
spring.thymeleaf.cache=false
spring.datasource.url=jdbc:postgresql://db:5432/questionnaire
spring.datasource.username=questionnaire
spring.datasource.password=questionnaire
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.jpa.show-sql=true
